### PR TITLE
Use rollup to make the browser bundle at build time

### PR DESCRIPTION
**Pull request by papandreou**
Demotes brfs to a dev dep

Fixes: #3

### CODE REVIEW

**Comment by AndreasMadsen** [comment]
Can you elaborate on what the problem with `browserify` is?

**Comment by papandreou** [comment]
Here's what I tried: https://github.com/papandreou/node-cephes/tree/chore/browserify

It fails with a pretty cryptic error (that file does exist):

```
Error: module not found: "/Users/andreaslind/work/node-cephes/index.js" from file /Users/andreaslind/work/node-cephes/_fake.js
    at onresolve (/Users/andreaslind/work/node-cephes/node_modules/module-deps/index.js:183:30)
    at /Users/andreaslind/work/node-cephes/node_modules/browserify/index.js:530:20
    at /Users/andreaslind/work/node-cephes/node_modules/browser-resolve/index.js:247:21
    at /Users/andreaslind/work/node-cephes/node_modules/browser-resolve/node_modules/resolve/lib/async.js:55:18
    at load (/Users/andreaslind/work/node-cephes/node_modules/browser-resolve/node_modules/resolve/lib/async.js:69:43)
    at onex (/Users/andreaslind/work/node-cephes/node_modules/browser-resolve/node_modules/resolve/lib/async.js:92:31)
    at /Users/andreaslind/work/node-cephes/node_modules/browser-resolve/node_modules/resolve/lib/async.js:22:47
    at FSReqCallback.oncomplete (fs.js:158:21)
make: *** [cephes-browser-bundled.js] Error 1
```

Then I remembered that rollup has served me well in the past, so I gave up. It's probably fixable, though, if you have a preference for browserify.

**Comment by papandreou** [comment]
@AndreasMadsen, do you have any concerns with rollup? I've had great experiences with it in other projects.

**Comment by AndreasMadsen** [comment]
@papandreou It is mostly a matter of not fragmenting what bundler we use across modules, as we use browserify extensively in other modules.

**Comment by papandreou** [comment]
@AndreasMadsen, OK, I took another stab at getting browserify to work: https://github.com/nearform/node-cephes/pull/5

**Comment by AndreasMadsen** [comment]
Closed in factor of https://github.com/nearform/node-cephes/pull/6

**Pull request closed without merging**
